spring:
  application:
    name: REST_Quest
  config:
    import: optional:file:.env.development[.properties]
  datasource:
    url: ${dbUrl}
    username: ${dbUserName}
    password: ${dbPassWord}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

custom:
  baseUrl: ${baseUrl:http://localhost:8080}
  jwt:
    payload:
      issuer: ${jwtIssuer:REST_Quest}
      subject-access-token: ${jwtAccessSubject:ACCESS_TOKEN}
      subject-refresh-token: ${jwtRefreshSubject:REFRESH_TOKEN}
      audience: ${jwtAudience:REST_Quest_USER}
    secrets:
      app-key: ${base64UuidKey:cmVzdC1xdWVzdC1qd3Qtc2VjcmV0LWtleS1tdXN0LWJlLWxvbmc=}
      vanilla-key: ${vanillaKey:REST_Quest}
    validations:
      access: ${accessTokenTime:3600}
      refresh: ${refreshTokenTime:1209600}
